spring:
  profiles:
    #active: daehwan-local
    active: prod

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  http:
    servlet:
      multipart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  thymeleaf:
    view-names: thymeleaf/*
    prefix: /templates/
    suffix: .html

cloud:
  aws:
    credentials:
      accessKey: AKIA2J56D2I7FQLGUX6L
      secretKey: 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
    s3:
      bucket: litebook-images
    region:
      static: ap-northeast-2
    stack:
      auto: false

--- #Production
spring:
  profiles: prod

  thymeleaf:
    cache: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true

  master:
    datasource:
      jdbcUrl: jdbc:mysql://27.96.134.60:3306/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
      username: timeline
      password: timeline123
      driver-class-name: com.mysql.cj.jdbc.Driver
      testOnBorrow: true

  slave:
    datasource:
      jdbcUrl: jdbc:mysql://27.96.134.60:3389/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
      username: root
      password: timeline123
      driver-class-name: com.mysql.cj.jdbc.Driver
      testOnBorrow: true

logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG


--- #hyerin-local
spring:
  profiles: hyerin-local

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true

  datasource:
    url: jdbc:mysql://localhost:3306/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: timeline
    password: timeline123

  thymeleaf:
    cache: false
    check-template-location: true


--- #daehwan-local
spring:
  profiles: daehwan-local

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      show_sql: true
      format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sns_dev
    password: 1234
    
    
  thymeleaf:
    cache: false
    check-template-location: true

logging:
  level:
    org:
      hibernate: info


--- #test
spring:
  profiles: test

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        enable_lazy_load_no_trans: true

  datasource:
    url: jdbc:mysql://localhost:3306/sns_timeline?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: timeline
    password: timeline123
